inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 8
  Exclude:
    - "db/migrate/*"

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10
  Exclude:
    - "db/migrate/*"

Metrics/AbcSize:
  Enabled: true
  Max: 20
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Enabled: true
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Exclude:
    - "db/migrate/*"

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/CaseLikeIf:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: true

RSpec:
  Enabled: true

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyMetadata:
  Enabled: false
